[maxmovie]
title = "맥스무비"
url = "https://www.maxmovie.com/"
entrySelector = "ul div li.content.clearfix"
titleSelector = "span.textBox.floatLeft > a:nth-child(1) > h4"
linkSelector = "span.textBox.floatLeft > a"
contentSelector = "span.textBox.floatLeft > a:nth-child(3) > p"
imageSelector = "span.imgBox.floatLeft a span.imgBox"
waitUntil = "networkidle"